# Generated by Django 5.1.4 on 2024-12-31 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_totp', '0003_add_timestamps'),
        ('users', '0002_student_timeout_until_student_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='totp_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='otp_totp.totpdevice'),
        ),
    ]
